const ProjectDetails = [
  {
    id: 1,
    title: "Toronto Hydro",
    description: "Utility Website",
    demoURL: "https://www.torontohydro.com/",
    codeURL: "https://www.torontohydro.com/",
    imageURL: "/images/toronto-hydro.png",
    isActive: true,
    isFeatured: true,
  },
  {
    id: 2,
    title: "IndieWares",
    description: "Side Project",
    demoURL: "https://react-dock.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/IndieWares",
    imageURL: "/images/indieWare.png",
    isActive: true,
    isFeatured: true,
  },
  {
    id: 3,
    title: "React Dock",
    description: "Side Project",
    demoURL: "https://react-dock.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/React-Dock",
    imageURL: "/images/react-dock.png",
    isActive: true,
    isFeatured: true,
  },
  {
    id: 4,
    title: "YelpCamp",
    description: "Side Project",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/my-portfolio",
    imageURL: "/images/yelp-camp.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 5,
    title: "Keeper - a Notes App",
    description: "Side Project",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/keepClone",
    imageURL: "/images/note-keeper.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 6,
    title: "Contacts",
    description: "Side Project",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/ContactCards",
    imageURL: "/images/Contact.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 7,
    title: "Drumkit",
    description: "Side Project",
    demoURL: "https://ajit-drum-kit.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/drumKit",
    imageURL: "/images/drumkit.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 8,
    title: "Dice Game",
    description: "Side Project",
    demoURL: "https://unruffled-rosalind-cd9459.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/diceGame",
    imageURL: "/images/dice.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 9,
    title: "TinDog",
    description: "Side Project",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/TinDog",
    imageURL: "/images/tindog.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 10,
    title: "InfinityJobs Portal",
    description: "Android Application",
    demoURL:
      "https://xd.adobe.com/view/8ad141e6-3305-409c-856e-273a783511cc-df82/grid/",
    codeURL: "https://github.com/sardars270/InfinityJobsPortal/tree/master",
    imageURL: "/images/infinity-Job.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 11,
    title: "GoCars",
    description: "Android Application",
    demoURL:
      "https://xd.adobe.com/view/2adad529-19a7-4d71-684f-2ad6a4d61a47-5ceb/grid/",
    codeURL: "https://github.com/ajitdhdharia/GOCars",
    imageURL: "/images/goCars.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 12,
    title: "MyCafe",
    description: "Android Application",
    demoURL: "https://github.com/ajitdhdharia/React-Dock",
    codeURL: "https://github.com/ajitdhdharia/MyCafe",
    imageURL: "/images/Mycafe.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 13,
    title: "GoCars Design",
    description: "Application Design",
    demoURL:
      "https://xd.adobe.com/view/2adad529-19a7-4d71-684f-2ad6a4d61a47-5ceb/grid/",
    codeURL: "",
    imageURL: "/images/goCars.png",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 14,
    title: "InfinityJobs Portal Design",
    description: "Application Design",
    demoURL:
      "https://xd.adobe.com/view/8ad141e6-3305-409c-856e-273a783511cc-df82/grid/",
    codeURL: "",
    imageURL: "/images/infinity-Job.png",
    isActive: true,
    isFeatured: false,
  },
];

export default ProjectDetails;
