const ProjectDetails = [
  {
    id: 1,
    title: "Toronto Hydro",
    description: "Utility Website",
    detailDescription:
      "Toronto Hydro Corporation is an electric utility that operates the electricity distribution system for the city of Toronto, Ontario, Canada. As of 2018, it serves approximately 772,000 customers and delivers approximately 19% of the electricity consumed in Ontario.",
    demoURL: "https://www.torontohydro.com/",
    codeURL: "https://www.torontohydro.com/",
    imageURL: "/images/toronto-hydro.png",
    isActive: true,
    isFeatured: true,
    data: [
      { label: "React", value: 90 },
      { label: "JS", value: 90 },
      { label: "HTML/JSP", value: 80 },
      { label: "CSS3", value: 80 },
      { label: "jQuery", value: 70 },
      { label: "HighChart", value: 30 },
      { label: "DataTables", value: 30 },

    ],
  },
  {
    id: 2,
    title: "IndieWares",
    description: "Side Project",
    detailDescription:
      "Developing personalized e-commerce platform, leveraging technologies like React and Node.js to create a responsive and feature-rich online shopping experience. Implementing innovative solutions for enhanced user interaction, secure transactions, and streamlined product management.",
    demoURL: "https://react-dock.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/IndieWares",
    imageURL: "/images/indieWare.png",
    isActive: true,
    isFeatured: true,
    data: [
      { label: "React", value: 90 },
      { label: "HTML", value: 80 },
      { label: "Bootstrap", value: 80 },
      { label: "NodeJS", value: 60 },
      { label: "ExpressJS", value: 70 },
      { label: "REST", value: 30 },
      { label: "MongoDB", value: 50 },
    ],
  },
  {
    id: 3,
    title: "React Dock",
    description: "Side Project",
    detailDescription:
      "Curated and developed a comprehensive showcase of React projects, highlighting diverse react skills and innovative projects.",
    demoURL: "https://react-dock.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/React-Dock",
    imageURL: "/images/react-dock.png",
    isActive: true,
    isFeatured: true,
    data: [
      { label: "React", value: 90 },
      { label: "Bootstrap", value: 80 },
      { label: "Javascript", value: 95 },
      { label: "SCSS", value: 85 },
    ],
  },
  {
    id: 4,
    title: "Camp-In",
    description: "Side Project",
    detailDescription:
      "Fullstack web app (MongoDB, Express, NodeJS) providing a persistent platform for browsing, creating and managing campgrounds and comments",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/my-portfolio",
    imageURL: "/images/yelp-camp.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "ExpressJS", value: 90 },
      { label: "NodeJS", value: 80 },
      { label: "MongoDB", value: 80 },
    ],
  },
  {
    id: 5,
    title: "Keeper - a Notes App",
    description: "Side Project",
    detailDescription: "A note taking application in react",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/keepClone",
    imageURL: "/images/note-keeper.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "React", value: 90 },
      { label: "Bootstrap", value: 80 },
      { label: "Javascript", value: 95 },
      { label: "CSS", value: 85 },
    ],
  },
  {
    id: 6,
    title: "Contacts",
    description: "Side Project",
    detailDescription: "",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/ContactCards",
    imageURL: "/images/Contact.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "React", value: 90 },
      { label: "Javascript", value: 95 },
      { label: "CSS", value: 85 },
    ],
  },
  {
    id: 7,
    title: "Drumkit",
    description: "Side Project",
    detailDescription: "",
    demoURL: "https://ajit-drum-kit.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/drumKit",
    imageURL: "/images/drumkit.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "Javascript", value: 95 },
      { label: "CSS", value: 80 },
      { label: "HTML", value: 85 },
    ],
  },
  {
    id: 8,
    title: "Dice Game",
    description: "Side Project",
    detailDescription: "",
    demoURL: "https://unruffled-rosalind-cd9459.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/diceGame",
    imageURL: "/images/dice.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "Javascript", value: 95 },
      { label: "CSS", value: 80 },
      { label: "HTML", value: 85 },
    ],
  },
  {
    id: 9,
    title: "TinDog",
    description: "Side Project",
    detailDescription: "",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/TinDog",
    imageURL: "/images/tindog.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "Javascript", value: 95 },
      { label: "CSS", value: 80 },
      { label: "HTML", value: 85 },
    ],
  },
  {
    id: 10,
    title: "InfinityJobs Portal",
    description: "Android Application",
    detailDescription: "",
    demoURL:
      "https://xd.adobe.com/view/8ad141e6-3305-409c-856e-273a783511cc-df82/grid/",
    codeURL: "https://github.com/sardars270/InfinityJobsPortal/tree/master",
    imageURL: "/images/infinity-Job.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "AdobeXD", value: 100 },
      { label: "UI/UX", value: 100 }
    ],
  },
  {
    id: 11,
    title: "GoCars",
    description: "Android Application",
    detailDescription: "",
    demoURL:
      "https://xd.adobe.com/view/2adad529-19a7-4d71-684f-2ad6a4d61a47-5ceb/grid/",
    codeURL: "https://github.com/ajitdhdharia/GOCars",
    imageURL: "/images/goCars.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "AdobeXD", value: 100 },
      { label: "UI/UX", value: 80 }
    ],
  },
  {
    id: 12,
    title: "MyCafe",
    description: "Android Application",
    detailDescription: "",
    demoURL: "https://github.com/ajitdhdharia/React-Dock",
    codeURL: "https://github.com/ajitdhdharia/MyCafe",
    imageURL: "/images/Mycafe.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "Android", value: 95 },
      { label: "JAVA", value: 80 },
      { label: "SQL", value: 85 },
    ],
  },
  {
    id: 13,
    title: "GoCars Design",
    description: "Application Design",
    detailDescription: "",
    demoURL:
      "https://xd.adobe.com/view/2adad529-19a7-4d71-684f-2ad6a4d61a47-5ceb/grid/",
    codeURL: "",
    imageURL: "/images/goCars.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "AdobeXD", value: 100 },
      { label: "UI/UX", value: 80 }
    ],
  },
  {
    id: 14,
    title: "InfinityJobs Portal Design",
    description: "Application Design",
    detailDescription: "",
    demoURL:
      "https://xd.adobe.com/view/8ad141e6-3305-409c-856e-273a783511cc-df82/grid/",
    codeURL: "",
    imageURL: "/images/infinity-Job.png",
    isActive: true,
    isFeatured: false,
    data: [
      { label: "AdobeXD", value: 100 },
      { label: "UI/UX", value: 80 }
    ],
  },
];

export default ProjectDetails;
