const ProjectDetails = [
  {
    id: 1,
    title: "IndieWares",
    description: "Side Project",
    demoURL: "https://react-dock.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/React-Dock",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: true,
  },
  {
    id: 2,
    title: "React Dock",
    description: "Side Project",
    demoURL: "https://react-dock.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/React-Dock",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: true,
  },
  {
    id: 3,
    title: "YelpCamp",
    description: "Javascript/jQuery/SASS/Bootstrap",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/my-portfolio",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 4,
    title: "My Portfolio",
    description: "ReactJs/Javascript/SASS/Bootstrap",
    demoURL: "https://www.ajitdhdharia.com/",
    codeURL: "https://github.com/ajitdhdharia/my-portfolio",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 5,
    title: "Keeper - a Notes App",
    description: "ReactJs/Javascript/HTML/CSS/Bootstrap/Sass",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/keepClone",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 6,
    title: "Contacts",
    description: "ReactJs/Javascript/HTML/CSS/Bootstrap",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/ContactCards",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 7,
    title: "Drumkit",
    description: "Side Project",
    demoURL: "https://ajit-drum-kit.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/drumKit",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: true,
  },
  {
    id: 8,
    title: "Dice Game",
    description: "Javascript/jQuery/HTML/CSS/Bootstrap",
    demoURL: "https://unruffled-rosalind-cd9459.netlify.app/",
    codeURL: "https://github.com/ajitdhdharia/diceGame",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 9,
    title: "TinDog",
    description: "HTML/CSS/Bootstrap",
    demoURL: "",
    codeURL: "https://github.com/ajitdhdharia/TinDog",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 10,
    title: "InfinityJobs Portal",
    description: "Android/JAVA/XML",
    demoURL:
      "https://xd.adobe.com/view/8ad141e6-3305-409c-856e-273a783511cc-df82/grid/",
    codeURL: "https://github.com/sardars270/InfinityJobsPortal/tree/master",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 11,
    title: "GoCars",
    description: "Android/JAVA/XML",
    demoURL:
      "https://xd.adobe.com/view/2adad529-19a7-4d71-684f-2ad6a4d61a47-5ceb/grid/",
    codeURL: "https://github.com/ajitdhdharia/GOCars",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 12,
    title: "MyCafe",
    description: "Android/JAVA/XML",
    demoURL: "https://github.com/ajitdhdharia/React-Dock",
    codeURL: "https://github.com/ajitdhdharia/MyCafe",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 13,
    title: "GoCars Design",
    description: "Adobe XD/Adobe Illustrator/Adobe Photoshop",
    demoURL:
      "https://xd.adobe.com/view/2adad529-19a7-4d71-684f-2ad6a4d61a47-5ceb/grid/",
    codeURL: "",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
  {
    id: 14,
    title: "InfinityJobs Portal Design",
    description: "Adobe XD/Adobe Illustrator/Adobe Photoshop",
    demoURL:
      "https://xd.adobe.com/view/8ad141e6-3305-409c-856e-273a783511cc-df82/grid/",
    codeURL: "",
    imageURL: process.env.PUBLIC_URL + "/images/blog-1.jpg",
    isActive: true,
    isFeatured: false,
  },
];

export default ProjectDetails;
